language: c
compiler:
- gcc
- clang
addons:
  apt:
    packages:
    - libtool
    - libssl-dev
    - libkrb5-dev
    - libpcap-dev
    - flex
    - bison

jobs:
  exclude:
  - os: osx
    compiler: gcc
os:
- linux
- osx
